sudo: required
dist: trusty

matrix:
    include:
        - compiler: gcc
          addons:
            apt:
                packages:
                    - g++-4.6
          env:
            - CXX=g++-4.6
            - COMPILER=g++
        - compiler: gcc
          addons:
            apt:
                packages:
                    - g++-4.7
          env:
            - CXX=g++-4.7
            - COMPILER=g++
        - compiler: gcc
          addons:
            apt:
                packages:
                    - g++-4.8
          env:
            - CXX=g++-4.8
            - COMPILER=g++
        - compiler: gcc
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-4.9
          env:
            - CXX=g++-4.9
            - COMPILER=g++
        - compiler: gcc
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-5
          env:
            - CXX=g++-5
            - COMPILER=g++
        - compiler: clang
          addons:
            apt:
                packages:
                    - clang-3.5
          env:
            - CXX=clang++-3.5
            - COMPILER=clang++
        - compiler: clang
          addons:
            apt:
                packages:
                 - clang-3.6
          env:
            - CXX=clang++-3.6
            - COMPILER=clang++
        # - compiler: clang
        #   addons:
        #     apt:
        #         sources:
        #             - llvm-toolchain-precise-3.7
        #         packages:
        #          - clang-3.7
        #   env:
        #     - CXX=clang++-3.7
        #     - COMPILER=clang++

install:
    - sudo pip install gcovr
before_script:
    - python waf configure --coverage --check-cxx-compiler=$COMPILER
    - python waf build
script:
    - python waf test --coverage
